
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432

development:
  <<: *default
  database: file_app_developmet
  username: postgres
  password: postgres

test:
  <<: *default
  database: file_app_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: file_app_production
  username: postgres
  password: postgres